### ISSUE TITLE
Crash if you challenge the bot in a PM

### ISSUE THREAD

**Issue by GustavPersson** [PaulAsjes/kartbot#1]
``` javascript
/Users/gustavpersson/develop/kartbot/index.js:161
  var pool = members.concat();
                    ^

TypeError: Cannot read property 'concat' of undefined
    at challenge (/Users/gustavpersson/develop/kartbot/index.js:161:21)
    at Client.<anonymous> (/Users/gustavpersson/develop/kartbot/index.js:71:18)
    at emitOne (events.js:77:13)
    at Client.emit (events.js:169:7)
    at Client.onMessage (/Users/gustavpersson/develop/kartbot/node_modules/slack-client/src/client.js:479:14)
    at WebSocket.<anonymous> (/Users/gustavpersson/develop/kartbot/node_modules/slack-client/src/client.js:140:24)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.self._receiver.ontext (/Users/gustavpersson/develop/kartbot/node_modules/slack-client/node_modules/ws/lib/WebSocket.js:697:10)
    at Receiver.opcodes.1.finish (/Users/gustavpersson/develop/kartbot/node_modules/slack-client/node_modules/ws/lib/Receiver.js:397:14)
FAIL
```

**Comment by PaulAsjes-zz** [comment]
Fixed!
